api:
  id: "18396044"
  name: "limaone-elphi-credco-proxy-api"
  version: "v1"

keystore:
  storePassword: "ZtaAw5mSpn8E" 
  keyPassword: "ZtaAw5mSpn8E" 
  alias: "limaone"

corelogic:
  userName:  "RdZUnoKU3h2bOAo6QfR1ginrF6bMWdaK" 
  password: "hwZjIYnfEAphpGeD"
  host: "uat1.globalgateway.corelogic.com"
  token_host: "api-uat.corelogic.com"
  token_URL: "/order-gateway-oauth2/token"
  submit_URL: "/order/creditservicerequest/credit?action=Submit"
  reissue_URL: "/order/creditservicerequest/credit?action=Reissue"
  loginAccountIdentifier: "4004130"
  loginAccountPassword: "ZRQ6GKHY"
  authorization: "Basic UmRaVW5vS1UzaDJiT0FvNlFmUjFnaW5yRjZiTVdkYUs6aHdaaklZbmZFQXBocEdlRA=="
  
default:
  legalEntityName: "Lima One Capital"
  requestingPartyRoleType: "RequestingParty"
  
cache:
  maxEntries: "100"
  entryTtl: "30"
  expirationInterval: "30"