api:
  id: "18750662"
  name: "limaone-elphi-credco-api"
  version: "v1"

keystore:
  storePassword: "ZtaAw5mSpn8E" 
  keyPassword: "ZtaAw5mSpn8E" 
  alias: "limaone"
  
corelogic:
  userName:  "deEXlOwaSNAuOe3Ip0FQeinAOuQW3ClJ" 
  password: "fHGGqLd1IKyOCPkA"
  host: "globalgateway.corelogic.com"  
  token_host: "api-prod.corelogic.com"
  token_URL: "/order-gateway-oauth2/token"
  submit_URL: "/order/creditservicerequest/credit?action=Submit"
  reissue_URL: "/order/creditservicerequest/credit?action=Reissue"
  loginAccountIdentifier: "4586416"
  loginAccountPassword: "XFMPRHQ4"
  authorization: "Basic ZGVFWGxPd2FTTkF1T2UzSXAwRlFlaW5BT3VRVzNDbEo6ZkhHR3FMZDFJS3lPQ1BrQQ=="  
  
default:
  legalEntityName: "Lima One Capital"
  requestingPartyRoleType: "RequestingParty"
  
cache:
  maxEntries: "100"
  entryTtl: "30"
  expirationInterval: "30"